Repository climateconnect/climateconnect, pull requests merged in 2025-04, with the labels that each got.

#1502 hotfix infinite search due to missing errorhandling
  backend/organization/serializers/project.py
  backend/organization/views/project_views.py
  frontend/pages/editProject/[projectUrl].tsx
  frontend/public/lib/filterOperations.ts
Labels: PR: looking for reviewer

#1516 remove getHubTheme from projects page
  frontend/pages/projects/[projectId].tsx
Labels: PR: looking for reviewer

#1454 fixed the shared organization url for prio1
  frontend/pages/hubs/[hubUrl].tsx
  frontend/pages/organizations/[organizationUrl].tsx
  frontend/public/lib/hubOperations.ts
  frontend/src/components/account/AccountPage.tsx
  frontend/src/components/communication/MessageContent.tsx
  frontend/src/components/indexPage/hubsSubHeader/HubLinks.tsx
  frontend/src/components/shareContent/SocialMediaShareButton.tsx
Labels: PR: changes requested

#1529 removed raffleterms
  frontend/pages/raffleterms.tsx
Labels: PR: looking for reviewer

#1519 Removed unused props from wide layout
  frontend/pages/browse.tsx
  frontend/pages/editProject/[projectUrl].tsx
  frontend/pages/manageOrganizationMembers/[organizationUrl].tsx
  frontend/pages/manageProjectMembers/[projectUrl].tsx
  frontend/pages/share.tsx
  frontend/src/components/webflow/WebflowPage.tsx
Labels: PR: in progress

#1525 Added delete button to the project page on small device
  frontend/public/texts/project_texts.tsx
  frontend/src/components/editProject/DeleteProjectButton.tsx
  frontend/src/components/editProject/EditProjectContent.tsx
  frontend/src/components/general/NavigationButtons.tsx
Labels: PR: looking for reviewer

#1518 Updated `manageProjectMembers.tsx` to support custom hubs
  frontend/pages/hubs/[hubUrl].tsx
  frontend/pages/manageProjectMembers/[projectUrl].tsx
  frontend/src/components/layouts/layout.tsx
  frontend/src/components/project/ManageProjectMembers.tsx
  frontend/src/components/project/ProjectPageRoot.tsx
  frontend/src/components/project/ProjectTeamContent.tsx
Labels: PR: approved
